INSERT INTO category values (1, 'Wszystko');
INSERT INTO category values (2, 'Sprzedam');
INSERT INTO category values (3, 'Kupię');
INSERT INTO category values (4, 'Oddam');
INSERT INTO category values (5, 'Wykonam');
INSERT INTO category values (6, 'Zlecę');
INSERT INTO category values (7, 'Korepetycje');
INSERT INTO category values (8, 'Miasto');
INSERT INTO category values (9, 'Uczelnia');